calladitionalinfo:
    path:     /
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:index" }

calladitionalinfo_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:show" }

calladitionalinfo_new:
    path:     /new
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:new" }

calladitionalinfo_create:
    path:     /create
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:create" }
    requirements: { _method: post }

calladitionalinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:edit" }

calladitionalinfo_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:update" }
    requirements: { _method: post|put }

calladitionalinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeMinticBundle:CallAditionalInfo:delete" }
    requirements: { _method: post|delete }
